openapi: 3.0.0
info:
  title: Bedrock API
  version: 1.0.0
paths:
  /auth/signup:
    post:
      tags:
        - User Authentication
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'
components:
  schemas:
    SignupRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    SignupResponse:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
